export type Recommendation = "Apply Now" | "Tailor First" | "Risky" | "Skip"

export const jobs = [
  {
    id: "stripe-backend-engineer",
    company: "Stripe",
    role: "Software Engineer, Backend",
    location: "San Francisco, CA · Hybrid",
    salary: "$160K–$220K",
    visa: "H-1B Sponsor",
    match: 96,
    sponsorConfidence: 98,
    replyTime: "1-2 weeks",
    ghostRate: "Low",
    recommendation: "Apply Now" as Recommendation,
    logo: "S",
    logoClassName: "bg-gradient-to-br from-[#6C5CFF] to-[#3B30CC] text-white",
    reasons: ["Strong backend engineering experience with distributed systems", "You've built APIs and payment-related integrations", "Based in the US and open to hybrid roles"],
  },
  {
    id: "linear-software-engineer",
    company: "Linear",
    role: "Software Engineer",
    location: "New York, NY · Remote",
    salary: "$140K–$190K",
    visa: "H-1B Sponsor",
    match: 93,
    sponsorConfidence: 94,
    replyTime: "1 week",
    ghostRate: "Very Low",
    recommendation: "Tailor First" as Recommendation,
    logo: "L",
    logoClassName: "bg-[#111318] text-white",
    reasons: ["Strong sponsor signal", "Product engineering keywords need a tighter resume match", "Remote policy fits your preferences"],
  },
  {
    id: "ramp-senior-software-engineer",
    company: "Ramp",
    role: "Senior Software Engineer",
    location: "New York, NY · Hybrid",
    salary: "$150K–$210K",
    visa: "H-1B Sponsor",
    match: 91,
    sponsorConfidence: 91,
    replyTime: "1-2 weeks",
    ghostRate: "Low",
    recommendation: "Apply Now" as Recommendation,
    logo: "R",
    logoClassName: "bg-[#FFE300] text-[#111318]",
    reasons: ["Compensation clears sponsorship wage signal", "Recent filings are role-compatible", "Strong React and data workflow overlap"],
  },
  {
    id: "anthropic-applied-ai",
    company: "Anthropic",
    role: "Software Engineer, Core ML",
    location: "San Francisco, CA · Hybrid",
    salary: "$170K–$230K",
    visa: "H-1B Sponsor",
    match: 90,
    sponsorConfidence: 97,
    replyTime: "1-2 weeks",
    ghostRate: "Low",
    recommendation: "Tailor First" as Recommendation,
    logo: "AI",
    logoClassName: "bg-[#C7A27F] text-[#111318]",
    reasons: ["Sponsor signal is excellent", "AI/ML language needs more precise resume evidence", "Hybrid location fits your profile"],
  },
  {
    id: "notion-staff-software-engineer",
    company: "Notion",
    role: "Staff Software Engineer",
    location: "San Francisco, CA · Remote",
    salary: "$160K–$220K",
    visa: "H-1B Sponsor",
    match: 88,
    sponsorConfidence: 92,
    replyTime: "2 weeks",
    ghostRate: "Low",
    recommendation: "Apply Now" as Recommendation,
    logo: "N",
    logoClassName: "bg-black text-white",
    reasons: ["Strong product engineering overlap", "Healthy sponsor history", "Remote-friendly signal is strong"],
  },
  {
    id: "vercel-fullstack-engineer",
    company: "Vercel",
    role: "Software Engineer, Fullstack",
    location: "San Francisco, CA · Hybrid",
    salary: "$140K–$200K",
    visa: "H-1B Sponsor",
    match: 87,
    sponsorConfidence: 91,
    replyTime: "1 week",
    ghostRate: "Very Low",
    recommendation: "Apply Now" as Recommendation,
    logo: "▲",
    logoClassName: "bg-black text-white",
    reasons: ["Framework experience lines up", "Good sponsorship history", "Salary and role level clear the risk threshold"],
  },
  {
    id: "figma-software-engineer",
    company: "Figma",
    role: "Software Engineer",
    location: "Remote · US",
    salary: "$150K–$210K",
    visa: "H-1B Sponsor",
    match: 85,
    sponsorConfidence: 86,
    replyTime: "1-2 weeks",
    ghostRate: "Low",
    recommendation: "Tailor First" as Recommendation,
    logo: "F",
    logoClassName: "bg-gradient-to-br from-[#FF7262] via-[#A259FF] to-[#1ABCFE] text-white",
    reasons: ["Recent graduate friendly", "Strong design systems overlap", "Resume needs more collaboration evidence"],
  },
]

export const sponsorCompanies = [
  { company: "Stripe", approvals: 1842, medianWage: "$176K", replyTime: "2.1 days", ghostRate: "6%", confidence: 98, openRoles: 132 },
  { company: "Anthropic", approvals: 1203, medianWage: "$168K", replyTime: "1.8 days", ghostRate: "5%", confidence: 97, openRoles: 78 },
  { company: "Linear", approvals: 623, medianWage: "$145K", replyTime: "1.6 days", ghostRate: "7%", confidence: 94, openRoles: 41 },
  { company: "Microsoft", approvals: 4813, medianWage: "$155K", replyTime: "2.6 days", ghostRate: "10%", confidence: 90, openRoles: 312 },
  { company: "Amazon", approvals: 4501, medianWage: "$152K", replyTime: "2.9 days", ghostRate: "11%", confidence: 89, openRoles: 523 },
]

export const applications = [
  { company: "Stripe", role: "Backend Engineer", status: "Saved", date: "Added 5 days ago", confidence: 98 },
  { company: "NVIDIA", role: "Data Scientist", status: "Tailoring", date: "Updated 1 day ago", confidence: 96 },
  { company: "Amazon", role: "SDE II", status: "Applied", date: "Applied 3 days ago", confidence: 89 },
  { company: "Microsoft", role: "Software Engineer", status: "Under Review", date: "Replied in 5 days", confidence: 90 },
  { company: "Google", role: "Software Engineer", status: "Interview", date: "Onsite · May 29", confidence: 81 },
  { company: "Intuit", role: "Software Engineer", status: "Offer", date: "May 20, 2025", confidence: 86 },
  { company: "Tesla", role: "Data Scientist", status: "Rejected", date: "2 weeks ago", confidence: 41 },
]
