import { ApplyfastLogo, ApplyfastMark } from '@/components/brand/Logo';
import { Badge, Button, Card, Input, MetricCard, ProgressRing } from '@/components/ui/Core';
import { JobCard } from '@/components/product/JobCard';
import { CompanyRow } from '@/components/product/CompanyRow';
import { DecisionPanel } from '@/components/product/DecisionPanel';
import { ResumeDiff } from '@/components/product/ResumeDiff';
import { TrackerKanban } from '@/components/product/Kanban';
import { jobs, companies } from '@/lib/mock';

export default function DesignSystem(){return <div className="page"><section className="dark" style={{padding:'34px 0 64px'}}><div className="container"><ApplyfastLogo/><h1 className="display" style={{margin:'46px 0 10px'}}>Applyfast coded design system.</h1><p className="body" style={{maxWidth:700,color:'#dce2e7'}}>Reusable React components, tokens, layouts, and product modules. This is the visual source of truth for coding agents.</p></div></section><main className="container section"><div className="grid" style={{gridTemplateColumns:'1.1fr .9fr'}}><Card><h2>Logo Suite</h2><div className="row"><ApplyfastLogo darkWord/><div className="surface" style={{padding:18,background:'#0D0F12'}}><ApplyfastLogo/></div><ApplyfastMark/></div></Card><Card><h2>Colors</h2><div className="row" style={{justifyContent:'flex-start',flexWrap:'wrap'}}>{[['Lime','#B7F34A'],['Charcoal','#0D0F12'],['Dark Gray','#1F2328'],['Muted','#9CA3AF'],['Soft','#F3F4F6'],['White','#FFFFFF']].map(([n,c])=><div key={n}><div style={{width:72,height:72,borderRadius:16,background:c,border:'1px solid #ddd'}}/><b>{n}</b><div className="caption">{c}</div></div>)}</div></Card></div><div className="grid" style={{gridTemplateColumns:'1fr 1fr',marginTop:20}}><Card><h2>Typography</h2><div className="display">Display</div><div className="h1">H1 Headline</div><div className="h2">H2 Section</div><p className="body">Body text uses generous line-height for readability.</p></Card><Card><h2>Controls</h2><div className="row" style={{justifyContent:'flex-start',flexWrap:'wrap'}}><Button>Primary →</Button><Button variant="dark">Dark</Button><Button variant="secondary">Secondary</Button><Badge tone="green">Sponsor Friendly</Badge><Badge tone="blue">Interview</Badge><Badge tone="orange">Risky</Badge><Badge tone="red">Skip</Badge></div><div className="grid" style={{gridTemplateColumns:'1fr 1fr',marginTop:16}}><Input placeholder="Default input"/><Input value="Focused input"/></div></Card></div><section className="section" style={{paddingBottom:0}}><h2 className="h1">Product components</h2><div className="grid" style={{gridTemplateColumns:'1fr 1fr',marginTop:20}}><Card><h3>Job Card</h3><JobCard job={jobs[0]} selected/></Card><Card><h3>Company Row</h3><CompanyRow company={companies[0]} selected/></Card><Card><h3>Metric Card</h3><MetricCard icon="✦" label="New Matches" value="24" change="26%"/></Card><Card><h3>Progress Ring</h3><ProgressRing value={96}/></Card></div></section><section className="section" style={{paddingBottom:0}}><h2 className="h1">Decision & workflow components</h2><DecisionPanel/><div style={{marginTop:20}}><ResumeDiff/></div></section><section className="section"><h2 className="h1">Tracker Kanban</h2><TrackerKanban/></section></main></div>}
